### ISSUE TITLE
media files

### ISSUE THREAD

**Issue by pyvandenbussche** [ipedrazas/taiga-docker#24] opened 2015-11-05 14:40 UTC
Hi a last questions hopefully ...
Now the front can discuss with the back. Files are written in taiga-back correctly but my browser can not access the media file with URL: http://DNS_back/media/user ...
Shall I edit anything for this query to point to media folder in taiga-back? 
Sorry I am not that knowledgeable here ...

**Comment by pyvandenbussche** [comment] 2015-11-05 17:20
To add a bit of context I am running taiga-front on 8080 port on the host.

**Comment by bluefalcon26** [comment] 2017-02-07 17:48
The problem is that the volume definitions in the backend Dockerfile are commented out.

`19 ## Volume definition in docker-compose.yml instead of here`
`20 # VOLUME ["/taiga/static","/taiga/media"]`

Since the docker-compose method has not been fully implemented yet, I recommend reincluding these lines for the time being.

**Comment by ipedrazas** [comment] 2017-10-21 07:51
closing

**Closed by ipedrazas** 2017-10-21 07:51 UTC
