### ISSUE TITLE
Bad Oompa Loompas.

### ISSUE THREAD

**Issue by damccull** [ipedrazas/taiga-docker#12] opened 2015-06-12 21:52 UTC
Installed docker on an ubuntu machine at digital ocean. Cloned this repo. Ran setup.sh. Ran run-taiga.sh. Connect to ipaddress:80. See login form. Login form redirects to /error after a second and shows "Something happened and our Oompa Loompas are working on it. Try reloading again soon." How do I fix?

**Comment by jhrocha** [comment] 2015-06-27 20:06
I had the same error.
Exists a solution?

**Comment by yves-christol** [comment] 2015-06-28 17:41
Hi there, I just had the same. Frustrating, the rest worked like a charm. I found it was probably about some localhost setting to be replaced with my server IP address, but I was not able where to put that in so far...

**Comment by sstraus** [comment] 2015-07-15 10:54
Same problem

**Comment by ipedrazas** [comment] 2015-07-20 22:06
The problem is because the frontend build. I'm refactoring the whole lot (and updating it to the latest taiga version). Hopefully, it will be fixed soon.

**Comment by yves-christol** [comment] 2015-07-21 16:23
Excellent news, thanks a lot Ivan, you're a king !

Yves

2015-07-21 0:06 GMT+02:00 Ivan Pedrazas <notifications@github.com>:

**Comment by ipedrazas** [comment] 2015-07-21 17:19
Right now It works but I need to update the doc.

**Comment by ceesco53** [comment] 2015-07-22 01:27
I'm totally not a python guru (php guy) and got this error just a few minutes ago.  I also used a fresh Digital Ocean Docker Droplet (14.04 ubuntu x64 / Docker 1.7.1).  Here is a python traceback during

-> Generate sample data
Trying import local.py settings...
Monkey patching...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/taiga/taiga/projects/management/commands/sample_data.py", line 117, in handle
    self.users.append(self.create_user(counter=x))
  File "/taiga/taiga/projects/management/commands/sample_data.py", line 351, in create_user
    full_name = full_name or "{} {}".format(self.sd.name('es'), self.sd.surname('es', number=1))
  File "/usr/local/lib/python3.4/site-packages/sampledatahelper/mixins/localized_mixin.py", line 33, in name
    return Name().generate(self, locale, number, as_list)
  File "/usr/local/lib/python3.4/site-packages/sampledatahelper/l10n/names.py", line 43, in generate
    names = self.get_names(locale)
  File "/usr/local/lib/python3.4/site-packages/sampledatahelper/l10n/names.py", line 24, in get_names
    self.__load_locale(locale)
  File "/usr/local/lib/python3.4/site-packages/sampledatahelper/l10n/names.py", line 19, in __load_locale
    Name.data[locale] = json.load(fd)
  File "/usr/local/lib/python3.4/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3925: ordinal not in range(128)
taiga-front
taiga-back
postgres
root@crossoff:~/taiga-docker# ls
backend  docker-compose.yml  frontend  install-docker.sh  LICENSE  README.md  run-taiga.sh  setup.sh
root@crossoff:~/taiga-docker# ./run-taiga.sh
postgres
taiga-back
taiga-front

**Comment by ipedrazas** [comment] 2015-07-22 07:56
Patience... The new taiga docker is coming. I just need to find some quiet time to finish it off :smile:

**Comment by ipedrazas** [comment] 2015-07-22 17:41
Everything should be fine now. Remember to delete your old containers.

**Comment by ceesco53** [comment] 2015-07-22 20:55
why does this step:

docker run --name postgres  postgres

run in the foreground now for me and not background? it's causing your setup script to hang for me at that step.

**Comment by ipedrazas** [comment] 2015-07-22 21:51
Oh, it must be because I forgot to put the -d flag ... :facepalm: :)

I've fixed it already. @ceesco53 are you running boot2docker?

**Comment by ceesco53** [comment] 2015-07-22 22:15
I am not using boot2docker - I'm using a digitalocean droplet which comes with ubuntu 14.04 / docker 1.7.1 preinstalled.  I'll edit my comment here in a few minutes when I get to my work laptop with the right ssh key on it...

**Comment by ipedrazas** [comment] 2015-07-22 22:26
Excellent!

Let me know how it goes

**Comment by ceesco53** [comment] 2015-07-22 23:53
@ipedrazas The setup.sh script worked flawlessly.  Well done!  Now I'm interested in best practices for updating the front/back-end/schema.  Maybe another thread or update the readme?  I'd appreciate the insight - being a docker noob for the foreseeable future.  Anyhow, I'd say you can close this ticket again.

**Comment by ipedrazas** [comment] 2015-07-23 09:07
@ceesco53 I guess that the answer to that question is "it depends", I would like to think that 3 containers are fully independent but that's not exactly true.

Anyway, happy that it did work for you.

**Closed by ipedrazas** 2015-07-23 09:07 UTC
